# Construyendo modelos con PyTorch

## `torch.nn.Module` y `torch.nn.Parameter`


`torch.nn.Module` es la clase base para cualquier red neuronal en PyTorch. Cualquier clase que herede de `torch.nn.Module` debe implementar el método `forward`. El método `forward` es el que define cómo se calcula la salida de la red neuronal.

Cualquier objeto de tipo `torch.nn.Module` registra todos los parámetros de la red neuronal (los pesos y los sesgos). Estos parámetros son objetos de tipo `torch.nn.Parameter`, que es una subclase de `torch.Tensor`. Los parámetros se pueden acceder a través del método `parameters()` de la clase `Module`.




A continuación se muestra un ejemplo de cómo definir una red neuronal muy básica en PyTorch. Esta red consta de dos capas lineales y una función de activación ReLU entre ellas. En ella podemos ver la estructura básica de una red neuronal en PyTorch, con un método `__init__()` que define las capas y otros componentes de la red, y un método `forward()` donde se realiza la computación.

In [3]:
import torch

class TinyModel(torch.nn.Module):
    
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(100, 200) # Capa de entrada
        self.activation = torch.nn.ReLU() # Función de activación
        self.linear2 = torch.nn.Linear(200, 10) # Capa de salida
        self.softmax = torch.nn.Softmax() # Función de salida
    
    def forward(self, x):
        x = self.linear1(x) 
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[-0.0329,  0.0004,  0.0033,  ..., -0.0296,  0.0088, -0.0540],
        [ 0.0028,  0.0299, -0.0915,  ...,  0.0280,  0.0159,  0.0241],
        [ 0.0849, -0.0265,  0.0135,  ...,  0.0054, -0.0537,  0.0781],
        ...,
        [ 0.0962, -0.0228,  0.0483,  ..., -0.0508,  0.0863,  0.0836],
        [ 0.0817,  0.0024, -0.0186,  ..., -0.0605,  0.0609,  0.0930],
        [ 0.0377,  0.0560,  0.0769,  ..., -0.0957, -0.0265,  0.0938]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0781,  0.0995, -0.0125, -0.0679, -0.0547,  0.0714, -0.0814,  0.0777,
        -0.0235,  0.0665,  0.0734,  0.0367,  0.0119,  0.0529, -0.0481, -0.0919,
         0.0495,  0.0223,  0.0138,  0.08

## Tipos de capas en PyTorch

### Capas lineales

El tipo más básico de capa de red neuronal es una capa *lineal* o *totalmente conectada*. Esta es una capa en la que cada entrada influye en cada salida de la capa en un grado especificado por los pesos de la capa. Si un modelo tiene *m* entradas y *n* salidas, los pesos serán una matriz *m* x *n*.

Se llama *lineal* porque la salida de la capa es una combinación lineal de las entradas $y=Wx+b$, donde $W$ es la matriz de pesos, $x$ es el vector de entradas y $b$ es el vector de sesgos.

Si tenemos 3 entradas $x_1$, $x_2$ y $x_3$ y 2 salidas $y_1$ y $y_2$, la salida de la capa será:

$$\begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = \begin{bmatrix} w_{11} & w_{12} & w_{13} \\ w_{21} & w_{22} & w_{23} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$$

In [17]:
lin = torch.nn.Linear(3, 2) # 3 entradas, 2 salidas

print('Parámetros de la capa (pesos y sesgos):')
for param in lin.parameters():
    print(param)

# Lo mismo accediendo directamente a cada atributo:
print('\n\nPesos:', lin.weight)
print('\n\nSesgos:', lin.bias)

x = torch.rand(1, 3) # Tensor de entrada de 1x3
print('\n\nInput:', x)

y = lin(x)
print('\n\nOutput:')
print(y)

Parámetros de la capa (pesos y sesgos):
Parameter containing:
tensor([[-0.2069,  0.2911, -0.0554],
        [-0.3530, -0.0932,  0.4839]], requires_grad=True)
Parameter containing:
tensor([-0.5717, -0.4867], requires_grad=True)


Pesos: Parameter containing:
tensor([[-0.2069,  0.2911, -0.0554],
        [-0.3530, -0.0932,  0.4839]], requires_grad=True)


Sesgos: Parameter containing:
tensor([-0.5717, -0.4867], requires_grad=True)


Input: tensor([[0.4343, 0.9277, 0.8893]])


Output:
tensor([[-0.4408, -0.2962]], grad_fn=<AddmmBackward0>)


Podemos ver que `lin.weight` contiene la matriz de pesos y que `lin.bias` contiene el vector de sesgos, siendo ambos de tipo `Parameter`.

`Parameter` es una subclase de `Tensor` que se utiliza para indicar que un tensor es un parámetro de una red neuronal y, por lo tanto, debe registrar los gradientes por el módulo de autograd de PyTorch. Esto es importante para que PyTorch pueda calcular los gradientes de los parámetros durante el entrenamiento.

## Fuentes

- https://pytorch.org/tutorials/beginner/introyt/modelsyt_tutorial.html