# Ejercicios Python 2


In [1]:
import numpy as np  # Para las versiones con NumPy

## Función que recibe una lista y devuelve otra eliminando sus duplicados


### Soluciones con listas


In [15]:
def elimina_duplicados_for(lista):
    """Recorriendo la lista y añadiendo a otra lista los elementos que no estén ya en ella"""
    lista2 = []
    for elem in lista:
        if elem not in lista2:
            lista2.append(elem)
    return lista2


def elimina_duplicados_comprehension(lista):
    """Idéntica a la anterior usando listas por comprehensión"""
    lista2 = []
    [lista2.append(elem) for elem in lista if elem not in lista2]
    return lista2


def elimina_duplicados_set(lista):
    """Convirtiendo a conjunto (un conjunto por definición no puede tener elementos repetidos).
    Pierde el orden de los elementos"""
    return list(set(lista))


def elimina_duplicados_enumerate(lista):
    """Usando enumerate para recorrer la lista y comprobar si el elemento está en la lista hasta el indice actual"""
    return [v for i, v in enumerate(lista) if v not in lista[:i]]


def elimina_duplicados_for_enumerate(lista):
    """Igual que el anterior, pero imperativo"""
    lista2 = []
    for i, v in enumerate(lista):
        if v not in lista[:i]:
            lista2.append(v)
    return lista2


# Test
print(elimina_duplicados_for_enumerate([1, 2, 3, 4, 5, 6, 7, 8, 9, 1]))
print(elimina_duplicados_for_enumerate([2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1]))
print(elimina_duplicados_set([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1]))
print(elimina_duplicados_for_enumerate([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2]))
print(
    elimina_duplicados_for_enumerate([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1])
)  # True == 1
print(
    elimina_duplicados_for_enumerate([1, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1])
)  # True == 1
print(elimina_duplicados_for_enumerate(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1]))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[True, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
['1', 2, 3, 4, 5, 6, 7, 8, 9, 1]


### Solución con NumPy


In [3]:
def elimina_duplicados_numpy(lista):
    return list(np.unique(lista))


# Test
print(elimina_duplicados_numpy([1, 2, 3, 4, 5, 6, 7, 8, 9, 1]))
print(
    elimina_duplicados_numpy([2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1])
)  # Numpy no mantiene el orden
print(elimina_duplicados_numpy([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2]))
print(elimina_duplicados_numpy([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1]))
print(elimina_duplicados_numpy([1, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1]))
print(elimina_duplicados_numpy(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1]))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
['1', '2', '3', '4', '5', '6', '7', '8', '9']


### Variante: eliminar duplicados de ndarrays


In [4]:
# No hace falta definir una nueva función. NumPy ya tiene una función para eliminar duplicados.

# Test
print(np.unique(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])))
print(
    np.unique(np.array([2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1]))
)  # Numpy no mantiene el orden
print(np.unique(np.array([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2])))

# En este caso ya asigna un 1 a True al crear el array y no al procesar con unique
array_test_tipos = np.array([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1])
print(array_test_tipos)
print(
    array_test_tipos.dtype
)  # Elige el tipo en el que "caben" todos los elementos (casteando)

print(np.unique(np.array([1, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1])))
print(np.unique(np.array(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1])))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 1 3 4 5 6 7 8 9 1 1 1]
int32
[1 2 3 4 5 6 7 8 9]
['1' '2' '3' '4' '5' '6' '7' '8' '9']


## Función que recibe una lista de listas y devuelve otra eliminando sus duplicados


In [5]:
def elimina_duplicados_en_sublistas(lista_sublistas):
    recorridos = set()
    nueva = []
    for sublista in lista_sublistas:
        nueva_sublista = []
        for elem in sublista:
            if elem not in recorridos:
                nueva_sublista.append(elem)
                recorridos.add(elem)
        nueva.append(nueva_sublista)
    return nueva


# Test
print(elimina_duplicados_en_sublistas([[1, 2, 3], [1, 5, 3], [1, 2, 3]]))
print(elimina_duplicados_en_sublistas([[1, 2, 3], [2, 3, 4], [4, 5, 6]]))

[[1, 2, 3], [5], []]
[[1, 2, 3], [4], [5, 6]]


## Función que recibe una matriz de NumPy y devuelve otra sustituyendo los valores repetidos por NaN


In [6]:
def elimina_duplicados_matriz_numpy(matriz: np.ndarray):
    matriz = matriz.astype(
        float
    )  # NaN es un indicador de que un elemento no es un número, pero es de tipo float
    ya_vistos = set()  # Conjunto de elementos
    for i, fila in enumerate(matriz):
        for j, elem in enumerate(fila):
            if elem in ya_vistos:
                matriz[i][j] = np.nan
            ya_vistos.add(elem)
    return matriz


array_t = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(elimina_duplicados_matriz_numpy(array_t))
print(array_t)

# Test
print(elimina_duplicados_matriz_numpy(np.array([[1, 1, 3], [3, 5, 7], [8, 2, 3]])))

[[ 1.  2.  3.]
 [nan nan nan]
 [nan nan nan]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 1. nan  3.]
 [nan  5.  7.]
 [ 8.  2. nan]]


## Función que recibe una lista y devuelve un diccionario con el número de veces que aparece cada elemento.

Las claves del diccionario deben ser los elementos de la lista y los valores deben ser el número de veces que aparece dicho elemento en la lista


### Solución con listas


In [7]:
def cuenta_elementos(lista):
    dicc = {}
    for elemento in lista:
        if elemento in dicc:
            dicc[elemento] += 1
        else:
            dicc[elemento] = 1
    return dicc


# Test
print(cuenta_elementos([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1]))
print(cuenta_elementos([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2]))
print(cuenta_elementos([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1]))  # True == 1
print(cuenta_elementos(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1]))

{1: 3, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{1: 5, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{True: 5, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{'1': 3, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 1: 2}


### Solución con NumPy


In [8]:
def valores_con_frecuencias(vector):
    return dict(zip(*np.unique(vector, return_counts=True)))


# Test
print(valores_con_frecuencias([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1]))
print(valores_con_frecuencias([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2]))
print(valores_con_frecuencias([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1]))
print(valores_con_frecuencias(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1]))

{1: 3, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{1: 5, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{1: 5, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{'1': 5, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1, '7': 1, '8': 1, '9': 1}


In [9]:
def valores_con_frecuencias(array: np.array):
    return dict((x, np.count_nonzero(array == x)) for x in array)


# Solo funciona específicamente con ndarrays ya que la igualdad array == x devuelve un array de booleanos

# Test
print(valores_con_frecuencias(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1])))
print(valores_con_frecuencias(np.array([1, 2, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2])))
print(
    valores_con_frecuencias(np.array([True, 2, True, 3, 4, 5, 6, 7, 8, 9, True, 1, 1]))
)
print(valores_con_frecuencias(np.array(["1", 2, "1", 3, 4, 5, 6, 7, 8, 9, "1", 1, 1])))

{1: 3, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{1: 5, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{1: 5, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}
{'1': 5, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1, '7': 1, '8': 1, '9': 1}


## Función que recibe dos matrices cuadradas (NxN) y devuelve una tercera matriz que contiene el valor 1 en las posiciones en que el valor de A y B coinciden y 0 en caso contrario.


### Soluciones con listas


In [10]:
def valores_iguales_matriz(matriz1, matriz2):
    matriz3 = []
    for i, fila in enumerate(matriz1):
        matriz3.append([])
        for j, elem in enumerate(fila):
            if elem == matriz2[i][j]:
                matriz3[i].append(1)
            else:
                matriz3[i].append(0)
    return matriz3


def valores_iguales_matriz_comprehension(matriz1, matriz2):
    return [
        [1 if elem == matriz2[i][j] else 0 for j, elem in enumerate(fila)]
        for i, fila in enumerate(matriz1)
    ]


# Tests
matriz1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # Matriz 3x3
lista_listas2 = [[1, 5, 6], [7, 5, 9], [1, 2, 9]]  # Matriz 3x3
print(
    valores_iguales_matriz(matriz1, lista_listas2)
)  # Debería mostrar una matriz identidad
assert valores_iguales_matriz(matriz1, lista_listas2) == [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
]

assert valores_iguales_matriz_comprehension(matriz1, lista_listas2) == [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


### Solución con NumPy


In [11]:
def valores_iguales_matriz_numpy(matriz1: np.array, matriz2: np.array):
    return np.where(matriz1 == matriz2, 1, 0)


# Tests
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Matriz 3x3
lista_listas2 = np.array([[1, 5, 6], [7, 5, 9], [1, 2, 9]])  # Matriz 3x3
print(
    valores_iguales_matriz_numpy(matriz1, lista_listas2)
)  # Debería mostrar una matriz identidad
assert np.array_equal(
    valores_iguales_matriz_numpy(matriz1, lista_listas2),
    [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
def valores_iguales_matriz_numpy(matriz1: np.array, matriz2: np.array):
    return (matriz1 == matriz2).astype(int)


# Tests
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Matriz 3x3
lista_listas2 = np.array([[1, 5, 6], [7, 5, 9], [1, 2, 9]])  # Matriz 3x3
print(
    valores_iguales_matriz_numpy(matriz1, lista_listas2)
)  # Debería mostrar una matriz identidad
assert np.array_equal(
    valores_iguales_matriz_numpy(matriz1, lista_listas2),
    [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Función que recibe una matriz y busca sus puntos de silla o _saddle points_ (máximos de su fila y mínimos de su columna o viceversa). Debe devolver una lista de tuplas con las coordenadas de los puntos de silla.


### Soluciones con listas


In [13]:
def find_saddle_points(matrix, only_max_row=True):
    """only_max_row=False: Busca los máximos de cada fila que son mínimos columna y también los mínimos de fila que son máximos de columna"""
    saddle_points = set()

    for irow, row in enumerate(matrix):  # Para cada fila
        # Buscamos los máximos de cada fila que son mínimos columna

        max_row = max(row)  # Máximo de esa fila
        i_max_row = [
            i for i, _ in enumerate(row) if row[i] == max_row
        ]  # Índices donde está ese máximo

        for i in i_max_row:  # Para cada índice donde está el máximo de la fila
            min_col_i = min(
                [row[i] for row in matrix]
            )  # Mínimo de la columna de ese máximo
            if (
                max_row == min_col_i
            ):  # Si el máximo de la fila es igual al mínimo de la columna en que está
                saddle_points.add((irow, i))

        if not only_max_row:  # Y en este caso, buscamos también los mínimos de cada columna que son máximos fila
            min_row = min(row)  # Mínimo de esa fila
            i_min_row = [
                i for i, _ in enumerate(row) if row[i] == min_row
            ]  # Índices donde está ese mínimo

            for i in i_min_row:
                max_col_i = max(
                    [row[i] for row in matrix]
                )  # Máximo de la columna de ese mínimo
                if min_row == max_col_i:
                    saddle_points.add((irow, i))

    return list(saddle_points)


def test_find_saddle_points():
    matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    assert find_saddle_points(matrix1) == [(0, 2)], "Falló el test 1a"
    assert find_saddle_points(matrix1, only_max_row=False) == [
        (0, 2),
        (2, 0),
    ], "Falló el test 1b"

    matrix2 = [[1, 2, 3], [3, 2, 1], [2, 2, 2]]
    assert find_saddle_points(matrix2) == [(2, 1)], "Falló el test 2a"
    # En este caso el la misma coordenada es máximo de fila y mínimo de columna y viceversa, con el set solo se añade una vez
    assert find_saddle_points(matrix2, only_max_row=False) == [
        (2, 1)
    ], "Falló el test 2b"

    # Test 3: matriz vacía
    assert find_saddle_points([]) == [], "Falló el test 3a"
    assert find_saddle_points([], only_max_row=False) == [], "Falló el test 3b"

    # Test 4: todos los elementos son iguales (todos son puntos de silla)
    matrix4 = [[5, 5, 5], [5, 5, 5]]
    assert sorted(find_saddle_points(matrix4)) == [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
    ], "Falló el test 4a"
    assert sorted(find_saddle_points(matrix4, only_max_row=False)) == [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
    ], "Falló el test 4b"

    matrix5 = [[1, 2, 3], [4, 5, 2], [3, 4, 5], [3, 4, 5], [4, 5, 5]]
    assert sorted(find_saddle_points(matrix5, only_max_row=False)) == [
        (4, 0)
    ], "Falló el test 5b"

    matrix6 = [[1, 4, 3, 3, 4], [2, 5, 4, 4, 5], [3, 2, 5, 5, 5]]
    assert sorted(find_saddle_points(matrix6, only_max_row=False)) == [
        (0, 4)
    ], "Falló el test 6b"

    matrix7 = [[1, 2, 6], [4, 5, 5], [3, 4, 5], [3, 4, 5], [4, 5, 5]]
    assert sorted(find_saddle_points(matrix7, only_max_row=False)) == [
        (1, 0),
        (1, 2),
        (2, 2),
        (3, 2),
        (4, 0),
        (4, 2),
    ], "Falló el test 7b"

    matrix8 = [[1, 4, 3, 3, 4], [2, 5, 4, 4, 5], [6, 5, 5, 5, 5]]
    assert sorted(find_saddle_points(matrix8, only_max_row=False)) == [
        (0, 1),
        (0, 4),
        (2, 1),
        (2, 2),
        (2, 3),
        (2, 4),
    ], "Falló el test 8b"

    print("Tests pasados con éxito")


test_find_saddle_points()

Tests pasados con éxito


Se ha separado la posibilidad de contemplar o no los mínimos de fila que son máximos de columna, ya que en la mayoría de aplicaciones se interpretan como puntos de silla solo los máximos de fila que son mínimos de columna. También se podrían calcular con el mismo algoritmo haciento la matriz transpuesta.

Esta solución está pensada para ser fácil de entender, pero podéis encontrar otras soluciones aquí:
https://exercism.org/tracks/python/exercises/saddle-points/solutions


### Solución con NumPy


In [14]:
def find_saddle_points(matrix: np.array, only_max_row=True):
    saddle_points = set()

    for irow, row in enumerate(matrix):
        max_row = row.max()
        for i in [i for i, _ in enumerate(row) if row[i] == max_row]:
            if max_row == matrix[:, i].min():
                saddle_points.add((irow, i))

        if not only_max_row:
            min_row = min(row)
            for i in [i for i, _ in enumerate(row) if row[i] == min_row]:
                if min_row == matrix[:, i].max():
                    saddle_points.add((irow, i))

    return list(saddle_points)


def test_find_saddle_points():
    matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    assert find_saddle_points(matrix1) == [(0, 2)], "Falló el test 1a"
    assert find_saddle_points(matrix1, only_max_row=False) == [
        (0, 2),
        (2, 0),
    ], "Falló el test 1b"

    matrix2 = np.array([[1, 2, 3], [3, 2, 1], [2, 2, 2]])
    assert find_saddle_points(matrix2) == [(2, 1)], "Falló el test 2a"
    # En este caso el la misma coordenada es máximo de fila y mínimo de columna y viceversa, con el set solo se añade una vez
    assert find_saddle_points(matrix2, only_max_row=False) == [
        (2, 1)
    ], "Falló el test 2b"

    # Test 3: matriz vacía
    assert find_saddle_points(np.array([])) == [], "Falló el test 3a"
    assert (
        find_saddle_points(np.array([]), only_max_row=False) == []
    ), "Falló el test 3b"

    # Test 4: todos los elementos son iguales (todos son puntos de silla)
    matrix4 = np.array([[5, 5, 5], [5, 5, 5]])
    assert sorted(find_saddle_points(matrix4)) == [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
    ], "Falló el test 4a"
    assert sorted(find_saddle_points(matrix4, only_max_row=False)) == [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
    ], "Falló el test 4b"

    matrix5 = np.array([[1, 2, 3], [4, 5, 2], [3, 4, 5], [3, 4, 5], [4, 5, 5]])
    assert sorted(find_saddle_points(matrix5, only_max_row=False)) == [
        (4, 0)
    ], "Falló el test 5b"

    matrix6 = np.array([[1, 4, 3, 3, 4], [2, 5, 4, 4, 5], [3, 2, 5, 5, 5]])
    assert sorted(find_saddle_points(matrix6, only_max_row=False)) == [
        (0, 4)
    ], "Falló el test 6b"

    matrix7 = np.array([[1, 2, 6], [4, 5, 5], [3, 4, 5], [3, 4, 5], [4, 5, 5]])
    assert sorted(find_saddle_points(matrix7, only_max_row=False)) == [
        (1, 0),
        (1, 2),
        (2, 2),
        (3, 2),
        (4, 0),
        (4, 2),
    ], "Falló el test 7b"

    matrix8 = np.array([[1, 4, 3, 3, 4], [2, 5, 4, 4, 5], [6, 5, 5, 5, 5]])
    assert sorted(find_saddle_points(matrix8, only_max_row=False)) == [
        (0, 1),
        (0, 4),
        (2, 1),
        (2, 2),
        (2, 3),
        (2, 4),
    ], "Falló el test 8b"

    print("Tests pasados con éxito")


test_find_saddle_points()

Tests pasados con éxito
