# NumPy para operaciones algebraicas

In [2]:
import numpy as np

## Matriz identidad

In [3]:
print(np.identity(4), "\n --- ") # Crea una matriz identidad de 4x4
print(np.eye(4), "\n --- ") # Lo mismo que np.identity(4)

# np.identity llama a np.eye con k=0. np.eye permite crear matrices con unos en la diagonal desplazados
print(np.eye(4, k=1), "\n --- ") # Crea una matriz de 2x3 con unos en la diagonal

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 --- 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 --- 
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 
 --- 


## Matriz transpuesta

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.T) # Transpuesta de A (intercambia filas y columnas)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [5]:
# Ciertas operaciones de acceso a slices de una matriz se pueden facilitar utilizando la transpuesta:
print(A[:,1]) # Columna 1
print(A.T[1]) # Fila 1 de la transpuesta = columna 1

[2 5]
[2 5]


## Operaciones con matrices

### Operaciones de matrices con escalares
Se pueden aplicar operaciones aritméticas a una matriz y un escalar. El escalar se aplica a cada elemento de la matriz.

[<img src="https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png" width="600">](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)

In [12]:
print(f"A=\n{A}")

print(f"A+3 =\n {A+3}") # Suma 3 a cada elemento de Y
print(f"A-3 =\n {A-3}") # Resta 3 a cada elemento de Y
print(f"A*2 =\n {A*2}") # Multiplica por 2 cada elemento de Y
print(f"A/2 =\n {A/2}") # Divide cada elemento de Y entre 2
print(f"A**2 =\n {A**2}") # Eleva al cuadrado cada elemento de Y
print(f"A**0.5 =\n {A**.5}") # Raíz cuadrada de cada elemento de Y (eleva a 1/2)
print(f"√.5 =\n {np.sqrt(A)}") # Raíz cuadrada de cada elemento de Y

A=
[[1 2 3]
 [4 5 6]]
A+3 =
 [[4 5 6]
 [7 8 9]]
A-3 =
 [[-2 -1  0]
 [ 1  2  3]]
A*2 =
 [[ 2  4  6]
 [ 8 10 12]]
A/2 =
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]
A**2 =
 [[ 1  4  9]
 [16 25 36]]
A**0.5 =
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
√.5 =
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Operaciones elemento a elemento
Se pueden sumar, restar, multiplicar o dividir los todos los elementos de dos matrices cada uno con su correspondiente.

[<img src="https://numpy.org/doc/stable/_images/np_sub_mult_divide.png" width="700"/>](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [7]:
X = np.identity(2, dtype=int)
print(f"X =\n{X}")
Y = np.array([[1, 2], [3, 4]])
print(f"Y =\n{Y}")
print("---")
print(f"X + Y =\n{X + Y}") # Suma de matrices
print(f"X - Y =\n{X - Y}") # Resta de matrices
print(f"X * Y =\n{X * Y}") # Producto elemento a elemento
print(f"X/Y =\n{X/Y}") # División elemento a elemento


X =
[[1 0]
 [0 1]]
Y =
[[1 2]
 [3 4]]
---
X + Y =
[[2 2]
 [3 5]]
X - Y =
[[ 0 -2]
 [-3 -3]]
X * Y =
[[1 0]
 [0 4]]
X/Y =
[[1.   0.  ]
 [0.   0.25]]


### **Multiplicación de matrices (producto matricial)**

El producto de matrices consiste en multiplicar cada fila de la primera matriz por cada columna de la segunda matriz, sumar los resultados y colocar el resultado en la posición correspondiente de la matriz resultante.

$$
X = \begin{pmatrix} 1 & 7 \\ 2 & 4 \end{pmatrix}
\qquad
Y = \begin{pmatrix} 3 & 3 \\ 5 & 2 \end{pmatrix}
$$
$$
X \times Y = 
\begin{pmatrix} 
    1 \times 3 + 7 \times 5 & 1 \times 3 + 7 \times 2 \\
    2 \times 3 + 4 \times 5 & 2 \times 3 + 4 \times 2
\end{pmatrix} =
\begin{pmatrix} 38 & 17 \\ 26 & 14 \end{pmatrix}
$$
Este ejemplo se ha sacado de [la khanacademy, donde podéis encontrar explicaciones de este proceso desde cero](https://es.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:multiplying-matrices-by-matrices/a/multiplying-matrices).

Es importante no confundir el producto matricial con el producto elemento a elemento.

**La multiplicación de matrices es una operación de vital importancia en computación**. Se utiliza en el procesamiento de imágenes, en el aprendizaje automático, en la criptografía, en la compresión de datos, en la simulación de sistemas físicos, en la resolución de sistemas de ecuaciones lineales, etc.

- [Por qué es importante la multiplicación de matrices](https://youtu.be/7V4E_GK1dt8?si=XPB8g7vwRX6beYRc&t=90)
- [Uso tensores y Numpy en redes neuronales](https://www.youtube.com/watch?v=bPPLCrjQCBQ)


In [8]:
X = np.array([[1, 7], [2, 4]]); print(f"X =\n{X}")
Y = np.array([[3, 3], [5, 2]]); print(f"Y =\n{Y}")
print("---")
print(f"X @ Y =\n{X @ Y}") # Producto matricial


X =
[[1 7]
 [2 4]]
Y =
[[3 3]
 [5 2]]
---
X @ Y =
[[38 17]
 [26 14]]


<!-- TODO: https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication -->
<!-- https://medium.com/@debopamdeycse19/dot-vs-matmul-in-numpy-which-one-is-best-suited-for-your-needs-dbd27c56ca33#:~:text=Comparison%20of%20Matmul%20and%20Dot,your%20specific%20problem%20and%20requirements. -->